[nixpacks]
  noBuildCache = false

[nixpacks.setup]
  pkgs = ["jdk21", "gradle"]

[nixpacks.build]
  cmd = "./gradlew clean build -x test"
  cachePaths = ["/root/.gradle"]

[nixpacks.start]
  cmd = "java -jar build/libs/agro-trace-backend-0.0.1-SNAPSHOT.jar"

[deploy]
  healthcheckPath = "/api/v1/actuator/health"
  restartPolicyType = "ON_FAILURE"
